@background = #1c242a
@foreground = #eeeFEB
@accentColor = #42bd7b
@selectionBackground = #244b3e
@selectionForeground = #f2f3ee
@disabledForeground = #77828a
@componentBackground = #151d23
@borderColor = #35424b
@buttonBackground = #252f37
@buttonHoverBackground = #303e46
@buttonPressedBackground = #1e4738
Panel.background = @background
RootPane.background = #11181d
TitlePane.background = #182127
TitlePane.inactiveBackground = #182127
TitlePane.foreground = @foreground
TitlePane.inactiveForeground = #a7b2ba
TitlePane.unifiedBackground = false
Component.arc = 8
Component.focusWidth = 1
Component.innerFocusWidth = 0
Component.borderColor = @borderColor
Component.focusColor = @accentColor
Component.hideMnemonics = false
Button.arc = 8
Button.margin = 7,16,7,16
Button.default.background = #218f59
Button.default.foreground = #ffffff
Button.default.hoverBackground = #29a568
Button.default.pressedBackground = #187547
Button.default.focusColor = @accentColor
TextComponent.arc = 8
TextField.margin = 5,8,5,8
ComboBox.padding = 5,8,5,8
ComboBox.buttonBackground = @buttonBackground
Spinner.padding = 5,8,5,8
Spinner.buttonBackground = @buttonBackground
TabbedPane.background = #151d23
TabbedPane.selectedBackground = #1c272b
TabbedPane.underlineColor = @accentColor
TabbedPane.inactiveUnderlineColor = @accentColor
TabbedPane.tabHeight = 46
TabbedPane.tabInsets = 8,24,8,24
TabbedPane.contentSeparatorHeight = 1
TabbedPane.contentAreaColor = #303b42
TabbedPane.focusColor = #2a3c35
Table.background = #192127
Table.alternateRowColor = #1d272d
Table.gridColor = #2b353d
Table.showHorizontalLines = false
Table.showVerticalLines = false
Table.cellMargins = 3,12,3,12
TableHeader.background = #232e35
TableHeader.foreground = #aeb8bf
TableHeader.separatorColor = #303b42
TableHeader.bottomSeparatorColor = #303b42
ScrollPane.border = 0,0,0,0
ScrollBar.width = 10
ScrollBar.track = #192127
ScrollBar.thumb = #3c4851
ScrollBar.thumbHoverColor = #56646c
ScrollBar.thumbArc = 999
ScrollBar.trackArc = 999
ScrollBar.thumbInsets = 2,2,2,2
Separator.foreground = #303b42
ProgressBar.background = #303b42
ProgressBar.foreground = @accentColor
ProgressBar.arc = 8
ToolTip.background = #263139
ToolTip.foreground = @foreground
